---
- name: Install 7-Zip manually on Windows
  hosts: windows_winrm
  gather_facts: no

  tasks:
    - name: Ensure C:\Temp directory exists
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - name: Copy 7-Zip installer to Windows host
      ansible.windows.win_copy:
        src: /ansible-lab/files/7z2301-x64.exe
        dest: C:\Temp\7z2301-x64.exe

    - name: Install 7-Zip silently
      ansible.windows.win_shell: |
        Start-Process -FilePath "C:\Temp\7z2301-x64.exe" -ArgumentList '/S' -Wait

    - name: Verify 7-Zip installation
      ansible.windows.win_stat:
        path: "C:\\Program Files\\7-Zip\\7z.exe"
      register: sevenzip_check

    - name: Show installation result
      ansible.builtin.debug:
        msg: >
          {%- if sevenzip_check.stat.exists -%}
          ✅ 7-Zip successfully installed!
          {%- else -%}
          ❌ 7-Zip installation failed.
          {%- endif -%}
