---
- name: Uninstall 7-Zip from Windows host
  hosts: windows_winrm
  gather_facts: no

  tasks:
    - name: Check if 7-Zip is installed
      ansible.windows.win_stat:
        path: "C:\\Program Files\\7-Zip\\Uninstall.exe"
      register: sevenzip_uninstaller

    - name: Uninstall 7-Zip silently
      ansible.windows.win_shell: |
        Start-Process -FilePath "C:\Program Files\7-Zip\Uninstall.exe" -ArgumentList '/S' -Wait
      when: sevenzip_uninstaller.stat.exists

    - name: Verify 7-Zip uninstallation
      ansible.windows.win_stat:
        path: "C:\\Program Files\\7-Zip\\7z.exe"
      register: sevenzip_check

    - name: Show uninstallation result
      ansible.builtin.debug:
        msg: >
          {%- if not sevenzip_check.stat.exists -%}
          ✅ 7-Zip successfully uninstalled!
          {%- else -%}
          ❌ 7-Zip uninstallation failed or still detected.
          {%- endif -%}
