---
- name: Deploy Zabbix Agent 2 to Windows hosts
  hosts: windows_winrm
  gather_facts: no

  vars:
    zabbix_server: "10.51.0.6"
    zabbix_serveractive: "10.51.0.6"
    tls_psk_identity: "YTLDCZBX01"
    tls_psk_value: "34bb50b346fbc39f4002851aa3ce33096e4dbbbc61890478d5e224229057ca9f"
    zabbix_msi: "zabbix_agent2-7.0.19-windows-amd64-openssl.msi"
    network_share: "\\\\MYDC1WD04\\installer\\zabbix_withproxy"
    remote_temp_path: "C:\\Temp"
    install_log: "C:\\Temp\\zabbix_install.log"

  tasks:
    - name: Ensure C:\Temp directory exists
      ansible.windows.win_file:
        path: "{{ remote_temp_path }}"
        state: directory

    - name: Copy Zabbix Agent MSI installer from network share
      ansible.windows.win_copy:
        src: "{{ network_share }}\\{{ zabbix_msi }}"
        dest: "{{ remote_temp_path }}\\{{ zabbix_msi }}"
        remote_src: yes

    - name: Install Zabbix Agent 2 silently with TLS and PSK
      ansible.windows.win_package:
        path: "{{ remote_temp_path }}\\{{ zabbix_msi }}"
        state: present
        arguments: >
          /l*v "{{ install_log }}"
          /qn /norestart
          SERVER={{ zabbix_server }}
          SERVERACTIVE={{ zabbix_serveractive }}
          TLSCONNECT=psk
          TLSACCEPT=psk
          TLSPSKIDENTITY={{ tls_psk_identity }}
          TLSPSKVALUE={{ tls_psk_value }}
          ENABLEPATH=1
          ALLOWDENYKEY="AllowKey=system.run[*]"
          HOSTNAME={{ ansible_hostname | default(inventory_hostname) }}
        log_path: "{{ install_log }}"

    - name: Wait for Zabbix Agent service to appear
      ansible.windows.win_service_info:
        name: "Zabbix Agent 2"
      register: zabbix_service_info
      retries: 5
      delay: 5
      until: zabbix_service_info.exists

    - name: Ensure Zabbix Agent 2 service is running
      ansible.windows.win_service:
        name: "Zabbix Agent 2"
        start_mode: auto
        state: started

    - name: Verify installation success
      ansible.windows.win_stat:
        path: "C:\\Program Files\\Zabbix Agent 2\\zabbix_agent2.exe"
      register: zabbix_check

    - name: Show installation result
      ansible.builtin.debug:
        msg: >
          {% if zabbix_check.stat.exists %}
          ✅ Zabbix Agent 2 installed and service started successfully.
          {% else %}
          ❌ Installation failed. Check {{ install_log }} for details.
          {% endif %}
